# Do not edit, autogenerated by scripts/codegen.py
import torch

def sigmoidcolon(x):
    return -0.0002086136487337328 * x ** 3 + 0.14139400205846075 * x ** 2 + -30.900376011785422 * x ** 1 + 2502.390934550166
    
    