# Do not edit, autogenerated by scripts/codegen.py
import torch

def sigmoidcolon(x):
    return -0.00019838297921413554 * x ** 3 + 0.13378547907766572 * x ** 2 + -29.00155803868406 * x ** 1 + 2345.683462308047
    
    